Library/Library/Controllers/BookController.cs
using Library.Business;
using Library.Business.Commands.Implementations.BookCommands;
using Library.Business.Queries.Interfaces;
using Library.Extensions;
using Library.Models.Books;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Library.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly IBookQueryService _bookQueryService;
        private readonly ICommandHandler<InsertBookCommand> _insertBookCommandHandler;
        private readonly ICommandHandler<UpdateBookCommand> _updateBookCommandHandler;
        private readonly ICommandHandler<DeleteBookCommand> _deleteBookCommandHandler;


        public BookController(IBookQueryService bookQueryService,
            ICommandHandler<InsertBookCommand> insertBookCommandHandler,
            ICommandHandler<UpdateBookCommand> updateBookCommandHandler,
            ICommandHandler<DeleteBookCommand> deleteBookCommandHandler)
        {
            _bookQueryService = bookQueryService;
            _insertBookCommandHandler = insertBookCommandHandler;
            _updateBookCommandHandler = updateBookCommandHandler;
            _deleteBookCommandHandler = deleteBookCommandHandler;

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Books()
        {
            var booksVM = _bookQueryService.GetAllBooks()
                                           .Select(bookDto => bookDto.ToBookVM());
            return View(booksVM);
        }

        public IActionResult AddBook()
        {
            var book = BookVM.GetBookModelWithGenres();
            return View(book);
        }

        [ValidFilter]
        [HttpPost]
        public async Task<IActionResult> AddBook(BookVM book)
        {
            var insertBookCommand = book.ToInsertBookCommand();
            insertBookCommand.SubmittedBy = HttpContext.User.GetUserId();

            await _insertBookCommandHandler.Handler(insertBookCommand);

            return RedirectToAction(nameof(Books));
        }

        public ActionResult EditBook(int id)
        {
            var bookVM = _bookQueryService.GetBookById(id)
                                          .ToBookVM();
            return View(bookVM);
        }

        [ValidFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBook(BookVM bookVM)
        {
            var updateBookCommand = bookVM.ToUpdateBookCommand();
            await _updateBookCommandHandler.Handler(updateBookCommand);

            return RedirectToAction(nameof(Books));
        }

        public ActionResult DeleteBook()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteBook(int id)
        {
            var book = _bookQueryService.GetBookById(id);

            var deleteBookCommandHandler = new DeleteBookCommand
            {
                BookId = book.BookId
            };

            await _deleteBookCommandHandler.Handler(deleteBookCommandHandler);

            return RedirectToAction(nameof(Books));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SearchBook(string SearchName)
        {
            var booksVM = _bookQueryService.GetBookByName(SearchName)
                                           .Select(book => book.ToBookVM());

            return View(nameof(Books), booksVM);
        }

        public IActionResult DownloadBook(int id)
        {
            var book = _bookQueryService.GetBookById(id);

            if (book.BookFile == null)
            {
                return View(nameof(NoPreview));
            }

            return File(book.BookFile, "application/pdf");
        }

        public IActionResult BookDetails(int id)
        {
            var bookVM = _bookQueryService.GetBookById(id)
                                          .ToBookVM();
            return View(bookVM);
        }

        public ActionResult NoPreview()
        {
            return View();
        }
    }

}

Library/Library/Controllers/LibraryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    [Authorize]
    public class LibraryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Library/Library/Controllers/UserController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Library.Business;
using Library.Business.Commands.Implementations.UserCommands;
using Library.Business.Queries.Interfaces;
using Library.Common.Enums;
using Library.Common.Utils;
using Library.Extensions;
using Library.Models.Users;
using Library.Resources;
using Microsoft.AspNetCore.Mvc;

namespace Library.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserQueryService _userQueryService;
        private readonly IBookQueryService _bookQueryService;
        private readonly ICommandHandler<InsertUserCommand> _insertUserCommandHandler;
        private readonly ICommandHandler<DeleteUserCommand> _deleteUserCommandHandler;
        private readonly ICommandHandler<UpdateUserCommand> _updateUserCommandHandler;

        public UserController(
            IUserQueryService userQueryService,
            IBookQueryService bookQueryService,
            ICommandHandler<InsertUserCommand> insertUserCommandHandler,
            ICommandHandler<DeleteUserCommand> deleteUserCommandHandler,
            ICommandHandler<UpdateUserCommand> updateUserCommandHandler)
        {
            _userQueryService = userQueryService;
            _bookQueryService = bookQueryService;
            _insertUserCommandHandler = insertUserCommandHandler;
            _deleteUserCommandHandler = deleteUserCommandHandler;
            _updateUserCommandHandler = updateUserCommandHandler;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Users()
        {
            var usersVM = _userQueryService.GetAllUsers()
                                           .Select(user => user.ToUserVMData());

            return View(usersVM);
        }

        public IActionResult AddUser()
        {
            var user = UserVM.GetUserWithMaritals();
            return View(user);
        }

        [ValidFilter]
        [HttpPost]
        public async Task<IActionResult> AddUser(UserVM userVM)
        {
            var existingUser = _userQueryService.GetUserByUsername(userVM.UserName);

            if (existingUser != null)
            {
                ViewBag.Message = LibraryControllerMessages.UserNameExists;
                var maritalValues = Enums.GetValues<Maritial>();
                var newList = maritalValues.ToSelectList();
                userVM.MaritalStatuses = newList;
                userVM.UserName = String.Empty;

                return View(userVM);
            }

            var insertUserCommand = userVM.ToInsertUserCommand();

            await _insertUserCommandHandler.Handler(insertUserCommand);

            return RedirectToAction(nameof(Users));
        }

        public ActionResult EditUser(int id)
        {
            var userVM = _userQueryService.GetUserById(id)
                                          .ToEditUserVMData();

            var maritalValues = Enums.GetValues<Maritial>();
            var maritalSelectList = maritalValues.ToSelectList();
            userVM.MaritalStatuses = maritalSelectList;

            return View(userVM);
        }


        [ValidFilter]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(EditUserVM editUserVM)
        {
            var updateUserCommand = editUserVM.ToUpdateUserCommand();
            await _updateUserCommandHandler.Handler(updateUserCommand);

            return RedirectToAction(nameof(Users));
        }

        public ActionResult DeleteUser()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteUser(int id)
        {
            var user = _userQueryService.GetUserById(id);

            var deleteUserCommand = new DeleteUserCommand
            {
                Id = id
            };

            await _deleteUserCommandHandler.Handler(deleteUserCommand);

            return RedirectToAction(nameof(Users));
        }

        public ActionResult DetailsUser(int id)
        {
            var booksVM = _bookQueryService.GetAllBooks()
                                           .Where(book => book.SubmittedBy == id)
                                           .Select(book => book.ToBookVM());

            return View(booksVM);
        }

    }
}

Library/Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
   
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Library</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Library")</li> 
                    <li>@Html.ActionLink("Books", "Books", "Book")</li>
                    <li>@Html.ActionLink("Users", "Users", "User")</li>
                    @Html.Partial("_LoginPartial.cshtml")
                </ul>
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Library</p>
        </footer>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
        <script>
            window.onload = function () {
                $('.book-genres').select2({
                    multiple: true,
                    placeholder:"Select book genres"
                });
            }
            $(document).ready(function () {
                $(".book-genres").select2();
            });
            //$(document).ready(function () {
            //    $('.book-genres').select2();
            //});

        </script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>